(function(z){
var WK=function(a,b,c){b="new"===(b||a.jd);return c?(a=a.d.u.v().get(z.U.rp),b?-1:-a):a.Vk+(b?-1:1)};var XK=function(a){z.Ev.call(this,a);this.Vk=0;this.jd="new"};var YK=function(a,b){a.XW=b};
var ZK=function(a){return(0,z.P)('\x3cdiv class\x3d"fyre '+(a.ke?"fyre-liveblog ":"")+(a.$g?"fyre-livechat ":"")+(a.wT?"fyre-bootstrap ":"")+(a.le?"fyre-mobile":"")+'"\x3e\x3cdiv class\x3d"fyre-widget '+(a.Va?"fyre-avatar-disabled":"")+'"\x3e'+(a.jv?z.mm(z.Ls(a)):"")+(0,z.P)('\x3cdiv class\x3d"fyre-featured-content-wrapper" style\x3d"display: none"\x3e\x3c/div\x3e')+'\x3cdiv class\x3d"fyre-stream-stats"\x3e\x3cdiv class\x3d"fyre-comment-count"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-help"\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-auth"\x3e\x3cdiv class\x3d"fyre-login-bar"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-live-container"\x3e\x3cdiv class\x3d"fyre-livecount"\x3e\x3c/div\x3e'+
(a.Va?"":'\x3cdiv class\x3d"fyre-listener-avatars"\x3e\x3c/div\x3e')+'\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-editor"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-input-box-collapsed"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-stream-header"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-comment-stream"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-top-content-stream"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-thread-breakout-stream"\x3e\x3c/div\x3e'+(a.$n?'\x3cdiv class\x3d"fyre-archive-stream-header"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-archive-stream"\x3e\x3c/div\x3e':
"")+'\x3cdiv class\x3d"fyre-stream-menu-container"\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e')};var $K=function(a){return(0,z.P)('\x3ca href\x3d"'+z.Q(z.R(a.Ea))+'" title\x3d"'+z.Q(a.Z)+'" data-id\x3d"'+z.Q(a.id)+'" class\x3d"fyre-follower fyre-follower-'+z.Q(a.eT)+'"\x3e\x3cimg src\x3d"'+z.Q(z.R(a.yd))+'" alt\x3d"'+z.Q(a.Z)+'" onerror\x3d"javascript:this.src\x3d\''+z.Q(z.Gm(a.Zb))+"';\" /\x3e\x3c/a\x3e")};
var aL=function(a){return(0,z.P)(z.Wq(a)+'\x3cdiv class\x3d"fyre-archive-stream-sort fyre-stream-sort"\x3e\x3ch3 class\x3d"fyre-archive-stream-title"\x3e\x3cstrong class\x3d"fyre-archive-stream-title-icon"\x3e\x3c/strong\x3e'+z.O(a.j.FN)+'\x3c/h3\x3e\x3cdiv class\x3d"fyre-stream-sort-options"\x3e\x3ca class\x3d"fyre-stream-sort-newest fyre-stream-sort-selected"\x3e'+z.O(a.j.Jx)+'\x3c/a\x3e\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+z.O(a.j.Io)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-oldest"\x3e'+
z.O(a.j.Kx)+"\x3c/a\x3e\x3c/div\x3e\x3c/div\x3e")};var bL=function(a){return(0,z.P)('\x3cdiv class\x3d"tooltip"\x3e'+z.O(a.message)+'\x3c/div\x3e\x3cdiv class\x3d"arrow-down"\x3e\x3c/div\x3e')};var cL=function(){};var dL=function(a){this.iG=!1;this.wo=[];this.yb=null;z.Gf.call(this,a)};var eL=function(a,b){z.Ij.call(this,b,a)};var fL=function(a,b){z.OF.call(this,a,b)};
var gL=function(a,b){var c=a.d.Bb;c.oh[4]&&(z.Xy(c,4,(0,z.t)(function(a){b.e(a,"threadBreakout",this.wr)},a)),z.Zy(c,4,(0,z.t)(function(a){b.Za(a,"threadBreakout",this.wr)})))};var hL=function(a,b){var c=[a.gm,a.$y];a.ug&&c.push(a.ug);a.at&&c.push(a.at);a.az&&c.push(a.az);z.x(c,function(a){z.Oo(a,"fyre-stream-sort-selected")});z.Mo(b,"fyre-stream-sort-selected")};var iL=function(a,b){z.OF.call(this,a,b)};
var jL=function(a,b){z.Ax.call(this,a,b);this.Zg=!1;this.oI=!!this.G.M.lG;this.Ga=new z.Ix;this.Ga.qc(this);this.Yt="archiveShowMore"};var kL=function(a,b){z.LF.call(this,a,b)};var lL=function(a,b,c){z.Zt.call(this,a,b,c);this.vz=b||"";this.rg(bL(this.s()))};var mL=function(a,b,c){z.Tt.call(this,a,b||3,c)};var nL=function(a,b){z.T.call(this,b);this.m=a};var oL=function(a,b){z.T.call(this,b);this.dc=a};var pL=function(a,b){oL.call(this,a,b)};
var qL=function(){var a=z.u.window,b=z.u.document;function c(){var a=A.elements;return"string"==typeof a?a.split(" "):a}function d(a){var b={},d=a.createElement,f=a.createDocumentFragment,g=f();a.createElement=function(a){A.BW||d(a);var c;c=b[a]?b[a].cloneNode():k.test(a)?(b[a]=d(a)).cloneNode():d(a);return c.canHaveChildren&&!h.test(a)?g.appendChild(c):c};a.createDocumentFragment=Function("h,f","return function(){var n\x3df.cloneNode(),c\x3dn.createElement;h.shivMethods\x26\x26("+c().join().replace(/\w+/g,
function(a){b[a]=d(a);g.createElement(a);return'c("'+a+'")'})+");return n}")(A,g)}function f(a){var b;if(a.MO)return a;if(A.AW&&!m){b=a.createElement("p");var c=a.getElementsByTagName("head")[0]||a.documentElement;b.innerHTML="x\x3cstyle\x3earticle,aside,details,figcaption,figure,footer,header,hgroup,nav,section{display:block}audio{display:none}canvas,video{display:inline-block;*display:inline;*zoom:1}[hidden]{display:none}audio[controls]{display:inline-block;*display:inline;*zoom:1}mark{background:#FF0;color:#000}\x3c/style\x3e";
b=!!c.insertBefore(b.lastChild,c.firstChild)}q||(b=!d(a));b&&(a.MO=b);return a}var g={},h=/^<|^(?:button|form|map|select|textarea|object|iframe)$/i,k=/^<|^(?:a|b|button|code|div|fieldset|form|h1|h2|h3|h4|h5|h6|i|iframe|img|input|label|li|link|ol|option|p|param|q|script|select|span|strong|style|table|tbody|td|textarea|tfoot|th|thead|tr|ul)$/i,m,q;(function(){var c=b.createElement("a");c.innerHTML="\x3cxyz\x3e\x3c/xyz\x3e";(m="hidden"in c)&&"function"==typeof a.qT&&a.qT("#modernizr{}",function(b){b.hidden=
!0;m="none"==(a.getComputedStyle?a.getComputedStyle(b,null):b.currentStyle).display});q=1==c.childNodes.length||function(){try{b.createElement("a")}catch(a){return!0}var c=b.createDocumentFragment();return"undefined"==typeof c.cloneNode||"undefined"==typeof c.createDocumentFragment||"undefined"==typeof c.createElement}()})();var A={elements:g.elements||"abbr article aside audio bdi canvas data datalist details figcaption figure footer header hgroup mark meter nav output progress section summary time video",
shivCSS:!1!==g.AW,shivMethods:!1!==g.BW,type:"default",shivDocument:f};f(b)};var rL=function(a,b){z.WF.call(this,a,b);a.M.FO||qL();var c=a.u.Mb(),d=a.u.v();this.ig=new z.MF(a,c,a.Il.Da,d.$g()||z.fg);this.D(this.ig);a.M.Va||(this.un=new pL(c),this.D(this.un));this.Dr=new z.KF;this.D(this.Dr)};var sL=function(a){var b=z.E.cb();return!a.w.ke()||b};var tL=function(a){z.fz.call(this,a);this.Lm=1};var uL=function(a){z.Os.call(this,a);z.hv(a.u);this.Qb=new rL(a);this.Kq.start();this.wl(this.Qb);z.Ss(this)};
var vL=function(a,b){this.LC=eL;this.sJ=uL;z.X.Mo(b.strings||{});z.xl.call(this,a,b)};var wL=function(a){a.kk&&(a.kk.p(),delete a.kk)};z.v(XK,z.Ev);z.e=XK.prototype;z.e.il=z.l(58);z.e.kF=z.l(60);z.e.lF=z.l(59);z.e.kF=z.K(60,function(a){this.Ja||(this.ro[a]=!1,z.Fv(this,a,function(a){a.N(a.xa.Km)}))});
z.e.lF=z.K(59,function(a,b){if(!this.Ja){var c=this.d.u.v(),d=z.Eu(a,b),f=c.get(z.U.vt);c.set(z.U.rp,d.IU);z.y(d.ab,(0,z.t)(this.d.R.N,this.d.R,"bootstrap_author_received"));d.content=z.lj(d.content,function(a,b){return!z.Ta(f,b)});z.y(d.content,function(a){z.jb(d.content,z.Hv(this,a))},this);z.jb(this.Cc,z.kj(d.content,z.Bb(a)));this.Xd(a,d.content);z.Fv(this,a,function(b){b.N(b.xa.Ak,{Id:a});b.set(b.k.df,!0)})}});
z.e.il=z.K(58,function(a,b){this.Vk=a;this.jd=b||this.jd;var c=this.Jd[a]=new z.Bv;z.Yu.C();var d=this.d.u.v(),f=(0,z.t)(this.lF,this,a),g=(0,z.t)(this.kF,this,a),h=this.d.M.Qm,d=d.get(z.U.Hc),h=z.w.Cu(d,h)+String(a)+".json";z.Zu(0,h,f,g);return c});z.rG.prototype.il=z.K(57,function(a,b){this.Jk||(this.Jk=new XK(this.G));var c=this.Jk,d=WK(c,a,b);return c.il(d,a)});z.Yu.prototype.Qh=z.K(49,function(a,b,c){a=z.wa("%s%scollection/%s/hot/",z.w.K.zd,z.w.af,a.na);(new z.Pe({url:a,wa:b,sa:c})).send()});
z.Vv.prototype.Qh=z.K(48,function(a){var b={na:this.d.u.v().id},c=z.Yu.C().Qh;z.Wv(this,c,b,a);return a});z.rG.prototype.Qh=z.K(47,function(){z.aw(this);this.Di=new z.Vv(this.G,void 0);var a=new z.Bv;this.Di.Qh(a);return a});z.Yu.prototype.Mh=z.K(46,function(a,b,c){a=z.wa("%s%scollection/%s/top/%s/",z.w.K.zd,z.w.af,a.na,a.zN);(new z.Pe({url:a,wa:b,sa:c})).send({format:"stream"})});z.Vv.prototype.Mh=z.K(45,function(a,b){var c={na:this.d.u.v().id,zN:a},d=z.Yu.C().Mh;z.Wv(this,d,c,b);return b});
z.rG.prototype.Mh=z.K(44,function(a){z.aw(this);this.Di=new z.Vv(this.G,void 0);var b=new z.Bv;this.Di.Mh(a,b);return b});z.T.prototype.xG=z.K(43,function(){return this.aa});z.Fj.prototype.$n=z.K(42,function(){return this.get(this.k.qp)});z.v(cL,z.Dl);z.da(cL);var xL={XX:"attachmentDelegate"};z.jb(xL,z.FG);cL.prototype.Xn=function(a){var b=cL.b.Xn.call(this,a),c=a.attachmentDelegate;c&&(b.HN=c);b.Dx=a[xL.vL]||null;return b};z.v(dL,z.Gf);dL.prototype.ST=function(a){this.yb||(this.yb=z.u.setInterval((0,z.t)(this.LP,this),5E3));this.wo=this.wo.concat(a)};
dL.prototype.LP=function(){this.wo.length&&(this.iG||(z.tc("//platform.twitter.com/impressions.js"),this.iG=!0),z.u.twttr=function(){var a=z.u.twttr||{},b=a.impressions||{};b._e=b._e||[];b.ready=b.ready||function(a){b._e.push(a)};a.impressions=b;return a}(),z.u.twttr.impressions.ready((0,z.t)(function(a){a.impressions.logTweets(this.wo,{partner:"livefyre"});this.wo=[]},this)))};dL.prototype.p=function(){(0,window.clearInterval)(this.yb);dL.b.p.call(this)};z.v(eL,z.Ij);eL.prototype.Ly=function(a){this.yi=new z.Uu(this);this.ju=new z.Mq(this,a);this.Jc=new z.Bi(this);this.bb=new z.qv(this,a);this.Il=new z.xv(this);this.u=new z.fv(this,a);this.Kb=new z.rG(this,a);new z.rf;this.Po=new z.ow(this,a);this.hz=new z.bw(this);this.qX=new dL(this);this.Bb=new z.Ny(this)};z.v(fL,z.OF);z.e=fL.prototype;z.e.s=function(){var a={},b=this.d.u,c=b.v();a.yx=b.v().ke();a.FU=!z.E.get(z.E.k.Sd);a.Bl=b.Bl(z.E.id);a.IO=2===c.get(z.U.Si);a.HO=3===c.get(z.U.Si);a.j={LT:z.X.get(z.X.g.Mt),OT:z.X.get(z.X.g.Nt),cT:z.X.get(z.X.g.NA),Jx:z.X.get(z.X.g.Kp),Kx:z.X.get(z.X.g.Lp),Io:z.X.get(z.X.g.QB),Zo:z.X.get(z.X.g.Pp),kX:z.X.get(z.X.g.hC)};return a};
z.e.J=function(a){fL.b.J.call(this,a);a=this.c;var b;b=this.s();var c=z.P,d=z.Wq(b),f;f=b.yx?(0,z.P)('\x3ca class\x3d"fyre-follow-conversation"\x3e'+(b.FU?b.Bl?z.O(b.j.OT):z.O(b.j.LT):"")+"\x3c/a\x3e"):"";b=c(d+f+'\x3cdiv class\x3d"fyre-stream-sort"\x3e\x3cdiv class\x3d"fyre-stream-sort-options"\x3e\x3ca class\x3d"fyre-stream-sort-newest fyre-stream-sort-selected"\x3e'+z.O(b.j.Jx)+'\x3c/a\x3e\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+z.O(b.j.Io)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-oldest"\x3e'+
z.O(b.j.Kx)+"\x3c/a\x3e"+(b.IO?'\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+z.O(b.j.Io)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-top-comments"\x3e'+z.O(b.j.kX)+"\x3c/a\x3e":"")+(b.HO?'\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+z.O(b.j.Io)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-hot-threads"\x3e'+z.O(b.j.cT)+"\x3c/a\x3e":"")+'\x3c/div\x3e\x3ca class\x3d"fyre-stream-sort-back"\x3e\x3c/a\x3e\x3c/div\x3e');a.innerHTML=b;this.hl=this.n("fyre-follow-conversation");this.at=this.n("fyre-stream-sort-hot-threads")||
null;this.az=this.n("fyre-stream-sort-top-comments")||null;this.ug=this.n("fyre-stream-sort-back");this.gm=this.n("fyre-stream-sort-newest");this.$y=this.n("fyre-stream-sort-oldest");this.tI=this.n("fyre-stream-sort-options");this.Yc=this.n("fyre-content-loading");this.Ed()};z.e.l=function(){fL.b.l.call(this);var a=this.q();z.E.on(z.E.xa.Mf,this.Rn,this);a.e(this.c,"click",this.ib);z.x([3,4,5],function(b){z.PF(this,a,b)},this);gL(this,a)};
z.e.ib=function(a){a.preventDefault();a=a.target;if(!z.So(a,"fyre-stream-sort-selected")&&"A"===a.tagName&&a!==this.ug)if(a===this.hl)this.jF();else switch(hL(this,a),this.fm(),a){case this.at:this.WD();break;case this.az:this.dispatchEvent({type:"sortTopComments",Ub:(0,z.t)(this.Ed,this)});break;case this.gm:this.hn("new");break;case this.$y:this.hn("old")}};z.e.vi=function(a,b){a&&this.My(b);z.Nn(this.tI,"display",a?"none":"block");z.Nn(this.ug,"display",a?"block":"none")};
z.e.My=function(a){var b=this.gm,c=this.hn,d=z.X.get(z.X.g.wt);4===a&&(b=this.at,c=this.WD,d=z.X.get(z.X.g.GJ));this.ug.innerHTML=d;this.q().wf(this.ug,"click",(0,z.t)(function(a){a.stopPropagation();this.vi(!1);hL(this,b);c.apply(this)},this))};z.e.On=function(a){a.stopPropagation();this.vi(!1);hL(this,this.gm);this.hn()};z.e.wr=function(a){var b=a.Ub;z.jb(a,{Ub:(0,z.t)(function(){b();this.vi(!0,4)},this)})};
z.e.hn=function(a){this.dispatchEvent({type:"sortOrderChanged",direction:a||"new",Ub:(0,z.t)(this.Ed,this)})};z.e.WD=function(){this.dispatchEvent({type:"sortHotThreads",Ub:(0,z.t)(this.Ed,this)})};z.e.jF=function(){var a=this.d.u;a.v();var b=z.E.k;z.E.id?(b=a.Bl(z.E.get(b.W)),a.sj(!b),a=b?z.X.get(z.X.g.Mt):z.X.get(z.X.g.Nt),this.hl.innerHTML=a):z.Sh(this.d.Jc,(0,z.t)(this.jF,this))};
z.e.Rn=function(){var a=this.d.u,b=a.v(),c=z.E.k,b=!b.ke()||z.E.get(c.Sd);this.hl&&(b?z.S(this.hl,!1):(a=a.Bl(z.E.id)?z.X.get(z.X.g.Nt):z.X.get(z.X.g.Mt),this.hl.innerHTML=a,z.S(this.hl,!0)))};z.e.h=function(){fL.b.h.call(this);z.E.off(null,null,this)};z.v(iL,fL);iL.prototype.J=function(a){this.c=a;z.Zl(a,aL,this.s());this.gm=this.n("fyre-stream-sort-newest");this.$y=this.n("fyre-stream-sort-oldest");this.tI=this.n("fyre-stream-sort-options");this.Yc=this.n("fyre-content-loading");this.Ed()};iL.prototype.hn=function(a){this.dispatchEvent({type:"archiveSortOrderChanged",stream:this.XW.stream,direction:a,Ub:(0,z.t)(this.Ed,this)})};
iL.prototype.s=function(){return{j:{FN:z.X.get(z.X.g.BJ),Jx:z.X.get(z.X.g.Kp),Kx:z.X.get(z.X.g.Lp),Io:z.X.get(z.X.g.QB),Zo:z.X.get(z.X.g.Pp)}}};z.v(jL,z.Ax);z.e=jL.prototype;z.e.Ym=function(a){this.clear();z.S(this.c,!0);this.jd=a};z.e.clear=function(){this.gd.Ld();this.ub={};this.zj=[];for(this.ph=this.Mk=null;this.ma&&0!=this.ma.length;)this.zo(0).p()};z.e.J=function(a){jL.b.J.call(this,a);z.Zl(this.c,z.Xq,this.s());this.ck=this.n("fyre-stream-content");this.wi=this.n("fyre-stream-more");this.Ga.S(this.wi);z.S(this.wi,!1)};z.e.h=function(){this.Ga&&this.Ga.p();this.Ga=null;jL.b.h.call(this)};
z.e.l=function(){jL.b.l.call(this);this.q().e(this.Ga,"showMore",this.Jw)};z.e.Lv=function(){return this.G.M.lG};z.e.s=function(){return{Rc:z.w.K.nb,cv:!!this.Ga,j:{Sy:z.X.get(z.X.g.CJ)}}};z.e.Kw=function(){this.Ga.Ws();this.Zg=!0};z.e.by=function(){this.dispatchEvent({type:this.Yt,direction:this.jd,target:this,yX:this.Zg&&this.oI,Ub:(0,z.t)(this.Kw,this),rj:(0,z.t)(this.IF,this)});this.Zg&&(this.oI=!1)};z.e.iy=function(a){this.Zg||jL.b.iy.call(this,a)};
z.e.Oo=function(){var a=this.G.Kb.Jk,b=this.jd,c=a.d.u.v(),b="old"===b,c=c.get(z.U.rp),c=!b&&a.Vk>-c;b&&-1>a.Vk||c?this.Ga.show():this.Ga.qb()};z.e.start=function(){this.Zg||this.by()};z.v(kL,z.LF);var yL=z.X.g,zL={};zL.comment=[yL.Fm,yL.Nf,yL.tm];zL.liveblog=[yL.XL,yL.jL,yL.TA];kL.prototype.GE=function(a){function b(a){return z.Ga(a,"%s")?a:"%s "+a}var c=this.m.ke()?"liveblog":"comment",c=zL[c];switch(a){case 1:c=b(z.X.get(c[1]));break;case 0:if(z.X.get(c[0])!==z.JF[c[0]]){c=z.X.get(c[0]);break}default:c=b(z.X.get(c[2]))}return z.wa(c,a)};z.v(lL,z.Zt);lL.prototype.Ro=200;lL.prototype.Sh=function(){return new mL(this.Ic)};lL.prototype.s=function(){var a={};a.message=this.vz;return a};z.v(mL,z.Tt);mL.prototype.Nc=function(a,b,c){var d=z.mo(this.element),d=new z.Ch(d.width,d.height+25);b=z.Ot(this.element,this.Fh,a,b,d,c,9);z.Tn(a.lastChild,0);b&&(d=new z.Ch(0,-5),z.Ot(this.element,2,a,1,d,c,5),z.Tn(a.lastChild,a.offsetWidth-(this.element.offsetParent.offsetWidth-this.element.offsetLeft+this.element.offsetWidth/2)))};z.v(nL,z.T);z.e=nL.prototype;z.e.r=function(){this.c=z.bm($K,this.s())};z.e.l=function(){nL.b.l.call(this);this.Ta=new lL(this.c,this.m.get("displayName"));this.q().e(this.c,"click",this.ib)};z.e.h=function(){nL.b.h.call(this);this.Ta&&this.Ta.p()};z.e.s=function(){var a=z.Wd,b={};b.yd=this.m.get(a.wb);b.Zb=this.m.get(a.rk);b.Z=this.m.get(a.ua);b.id=this.m.id;b.eT=this.m.id.replace(/[@.]/g,"-");b.Ea=this.m.get(a.Wb);return b};
z.e.ib=function(a){a.preventDefault();a.stopPropagation();this.dispatchEvent({t:this.m,type:"author_click"})};z.v(oL,z.T);z.e=oL.prototype;z.e.XA=10;z.e.h=function(){oL.b.h.call(this);delete this.dc};z.e.Q=function(){oL.b.Q.call(this);this.dc.off(null,null,this)};z.e.UE=function(a){a=new nL(a);var b=this.Mc();if(b===this.XA){var c=this.zo(b-1);c&&(c.p(),b--)}0<b?this.ze(a,0,!0):this.D(a,!0)};z.e.iS=function(a){var b;this.Tc(function(c){a.id===c.m.id&&(b=c)});b&&(this.removeChild(b),b.p())};
z.e.Yh=function(){this.dc.on(this.dc.xa.ut,this.UE,this);this.dc.on(this.dc.xa.Vt,this.iS,this);var a=this.dc.rb.reverse().slice(0,this.XA);z.x(a,this.UE,this)};z.v(pL,oL);z.v(rL,z.WF);
rL.prototype.MH=function(a,b){if(!this.Ja){this.w=b;var c=b.get(z.U.yh),d=b.get(z.U.Ud);this.ot=new z.TF(c,d,a.M.Va);this.D(this.ot);this.uq=new kL(a.u.v());this.D(this.uq);this.hs=null;b.$n()&&(this.uu=new iL(a),this.D(this.uu),this.Kk=new jL(a),this.D(this.Kk),YK(this.uu,{stream:this.Kk}));this.mh=new fL(a);this.D(this.mh);this.$r((0,z.t)(function(a){this.$b=a;this.D(this.$b);a=this.$b;this.aa&&a&&a.S(this.de,!0)},this));b.get(z.U.zm)&&!z.fg&&this.w.Rq()&&(this.w.$g()||this.w.ke()||this.mw())}};
rL.prototype.s=function(){var a=!this.d.M.kq&&!z.w.av&&!this.d.M.SD;return{SI:z.w.K.wz,TI:(0,window.encodeURIComponent)(String(window.location.href)),Va:this.d.M.Va,$g:this.w.$g(),ke:this.w.ke(),le:z.fg,jv:a,wT:this.d.M.kq,$n:this.w.$n()}};z.Ox={TX:"fyre-archive-stream",UX:"fyre-archive-stream-header",I0:"fyre-top-content-stream",a1:"fyre-widget",zm:"fyre-featured-content-wrapper"};z.jb(z.Ox,z.HJ);z.e=rL.prototype;
z.e.r=function(){this.c=z.bm(ZK,this.s());var a=this.w.get(z.U.Si);if(1!==a){var b=this.d.Bb,a=2===a?3:4,c=this.n("fyre-top-content-stream");z.Oy(b,a,c,this)}this.Dr.S(this.n(z.Ox.VK));this.Kk&&(b=this.n("fyre-archive-stream-header"),this.uu.S(b),this.Kk.S(this.n("fyre-archive-stream")));this.Gh(1);this.de=this.n(z.Ox.wh);b=sL(this);z.S(this.de,b)};
z.e.l=function(){rL.b.l.call(this);var a=this.$b;this.aa&&a&&a.S(this.de,!0);this.d.R.ap("stream_data_received",this.fR,this);this.q().e(this,"request_content_context",this.FQ).e(this,"request_content_reply",this.lS);this.Kk&&this.Kk.start()};z.e.Yh=function(){this.un&&this.un.Yh();this.ig.Yh()};z.e.fR=function(){var a=this.w,b=a.get(z.U.uk);z.th||b||(b=(0,z.t)(function(){this.hs=new z.AL(this.d,a.get(z.U.Ud));this.D(this.hs,!0)},this),z.tc(z.w.K.nb+z.w.yf.hs,null,null,b))};
z.e.mw=function(){var a=new z.CE(this.xG,this);a.oH=(0,z.t)(this.XV,this);var b=(0,z.t)(function(){a.start(0,2E3)},this);z.tc(z.w.K.nb+z.w.yf.oP,null,null,b)};z.e.XV=function(){var a=this.n("fyre-featured-content-wrapper");this.wv=new z.XJ(this.d);this.D(this.wv);this.wv.S(a);this.wv.Yg()};z.e.$r=function(a){if(!this.d.M.readOnly){var b=this.d.u.v();z.Jw(z.Gw.C(),"main",a,{G:this.d,oi:"new"},b);z.E.on(z.E.jc(z.E.k.W),this.Uc,this)}};z.e.Uc=function(){if(this.de){var a=sL(this);z.S(this.de,a)}};
z.e.Xh=function(){0<z.Do(this,this.$b)&&(this.removeChild(this.$b),this.$b.p());this.$r((0,z.t)(function(a){this.$b=a;this.D(this.$b);a=this.$b;this.aa&&a&&a.S(this.de,!0);z.S(this.de,!0)},this))};z.e.Wg=function(a){null!=a&&(this.d.Bb.nl(1),(0,window.setTimeout)((0,z.t)(function(){this.Ja||z.XF(this,a)},this),3E3))};z.e.FQ=function(a){z.XF(this,a.Qk)};z.e.lS=function(a){z.XF(this,a.Qk,function(a){z.Fw(a.Jb)})};
z.e.h=function(){rL.b.h.call(this);z.E.off(z.E.jc(z.E.k.W),this.Uc,this);this.w&&(this.w.off(null,null,this),this.w=null)};z.v(tL,z.fz);z.e=tL.prototype;z.e.he=function(a,b){tL.b.he.call(this,a,b);a.e(b,"repliesExpanded",this.gF);a.e(b,"sortHotThreads",this.vS);a.e(b,"sortOrderChanged",this.LF);a.e(b,"sortTopComments",this.wS);a.e(b,"archiveShowMore",this.pQ);a.e(b,"archiveSortOrderChanged",this.qQ)};
z.e.pQ=function(a){var b=a.Ub||z.n,c=(0,z.t)(this.Je,this,a.target),d=this.d.Kb;a=a.yX;d.Jk||(d.Jk=new XK(d.G));d=d.Jk;a=a?d.Vk:WK(d);var f=d.rd[a];f&&(d.Vk=a);if(f)b(),c(f);else{d=this.d.Kb.il();a=d.k.df;if(d.get(a))b();else d.on(d.jc(a),b,this);z.gz(this,d,c)}};z.e.hw=function(a,b){var c=2===b.Zc,d=1!==b.Zc;switch(b.type){case 0:var f=this.d.u.v(),f=z.xk(b,f),g=f.get(z.Kk),g=this.d.u.ab().get(g);f.set(z.yk,g);a.Aw(f,c,d)}};
z.e.DF=function(a){if(1!==this.Lm){var b=this.PW.mh;b.vi(!1);hL(b,b.gm);z.jb(a,{direction:"new",Ub:z.n});this.LF(a)}};z.e.qQ=function(a){z.hz(this);a.stream.Ym(a.direction);var b=this.d.Kb.il(a.direction,!0),c=(0,z.t)(function(b){a.Ub();this.Je(a.stream,b)},this);z.gz(this,b,c,a.rj)};z.e.LF=function(a){this.d.M.yl=null;var b=z.jz(this,1);z.aw(this.d.Kb);b.Ym(a.direction);var c=z.$v(this.d.Kb,a.direction),d=(0,z.t)(function(c){a.Ub();this.Je(b,c)},this);z.gz(this,c,d,a.rj)};
z.e.wS=function(a){var b=z.jz(this,3),c=this.d.Kb.Mh("likes");z.gz(this,c,(0,z.t)(function(c){a.Ub();z.gb(c)?z.zx(b):this.Je(b,c)},this))};z.e.vS=function(a){var b=z.jz(this,4),c=this.d.Kb.Qh();z.gz(this,c,(0,z.t)(function(c){a.Ub();z.gb(c)?z.zx(b):this.Je(b,c)},this))};z.v(uL,z.Os);z.e=uL.prototype;z.e.c=null;z.e.h=function(){uL.b.h.call(this);this.ct.p();this.mD.p();this.Qb.aa&&this.Qb.p();this.Lf&&this.Lf.p();delete this.Lf};z.e.wl=function(a){uL.b.wl.call(this,a);this.ct=new tL(this.d);this.ct.handle(a);this.mD=new z.cz(this.d);this.mD.handle(a)};z.e.iz=function(){this.d.yi.stop()};z.e.WW=function(){this.d.Il.stop()};z.e.$j=function(){this.d.yi.start()};z.e.TW=function(){this.d.Il.start()};
z.e.pa=function(){this.Lf&&this.Lf.p();this.Qb.pa(this.c);if("object"===typeof window.Livefyre&&window.Livefyre.rN)z.Ts(this);else{var a=z.Qs(this);this.Qb.Wg(a)}this.d.R.N("render_complete",this.c)};z.v(vL,z.xl);vL.prototype.EC=cL.C();vL.prototype.h=function(){vL.b.h.call(this);this.stop();delete this.M;delete this.ha;wL(this);z.Cl(this);this.qj&&(this.qj.p(),delete this.qj)};vL.prototype.qz=function(){this.stop();wL(this);vL.b.qz.call(this)};z.ng.main.Ih.ia(vL);})(fyre.conv);
